### PR TITLE
Add `--recursive` options in git-clone

### PR DESCRIPTION
**Pull request by nowsprinting**
There is a package with the source of the submodule inside.
So add `--recursive` option on `git clone`, be include submodule code.

Here are the packages you can check.
https://openupm.com/packages/com.vrmc.vrmshaders/

### CODE REVIEW

**Review by favoyang — CHANGES_REQUESTED** [review]
Thanks for the patch. Then shall also add `--shallow-submodules`, because `--depth=1` only applies to the base repo?

**Comment by nowsprinting** [comment]
Thanks! I didn't know this option.
I added this!

**Review by favoyang — APPROVED** [review]

**Comment by favoyang** [comment]
@nowsprinting do you think OpenUPM should rebuild the entire `com.vrmc.vrmshaders` version to include the Git submodules? Or we just do nothing but wait for the next release?

https://openupm.com/packages/com.vrmc.vrmshaders/?subPage=versions

**Comment by nowsprinting** [comment]
I think we can wait for the next release!
There should be a patch release soon, as there are other issues.

**Comment by favoyang** [comment]
Good to know, thank you.

**Pull request merged**
